# Generated by Django 5.2.3 on 2025-06-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
